### ISSUE TITLE
Incorrect behavior with GenericCellRatelimiter

### ISSUE THREAD

**Issue by ikonst** [sigmavirus24/rush#4]
I've tried using GenericCellRatelimiter in a simple fashion to throttle my client calls.

Here's some pytest code that reproduces the problem:
```py
import time
from collections import defaultdict
from datetime import datetime, timezone

import gevent
import pytest
from rush.limiters.gcra import GenericCellRatelimiter
from rush.limiters.periodic import PeriodicLimiter
from rush.quota import Quota
from rush.stores.dictionary import DictionaryStore
from rush.throttle import Throttle


@pytest.mark.parametrize('overflow_size', (
    pytest.param(1, id='1 extra item'),
    pytest.param(5, id='5 extra items'),
))
@pytest.mark.parametrize('limiter_class', (PeriodicLimiter, GenericCellRatelimiter))
def test_rate_limit(limiter_class, overflow_size):
    call_seconds = defaultdict(lambda: 0)

    rate_per_sec = 30

    throttle = Throttle(
        rate=Quota.per_second(rate_per_sec),
        limiter=limiter_class(DictionaryStore()),
    )

    def ensure_we_are_not_calling_too_fast(key):
        while True:
            result = throttle.check(key, 1)
            if not result.limited:
                break
            time.sleep(result.retry_after.total_seconds())

    def make_request():
        ensure_we_are_not_calling_too_fast('my_request')
        second = datetime.now(timezone.utc).replace(microsecond=0)
        call_seconds[second] += 1
        time.sleep(0)  # instead of requesting, we'll just yield (as network I/O would in e.g. gevent)

    gevent.joinall([
        gevent.spawn(make_request) for _ in range(rate_per_sec + overflow_size)
    ])

    expected_secs = 2
    assert len(call_seconds) >= expected_secs, f'expected calls to span at least {expected_secs} seconds'
```

Am I holding it wrong?

**Comment by sigmavirus24** [comment]
Could you explain what you're trying to test? 

I see that you're testing the PeriodicLimiter and GCRA limiter and testing what happens if you spawn `gevent` 31 or 35 times.

You also have a `defaultdict` named `call_seconds` which you're trying to determine the length of. You seem to be expecting there to be at least 2 entries there. So what I'm not sure is what you expect to see there or what you are seeing. (And I frankly don't have very much time to set up an environment in the next 5 minutes to re-run your test.)

Could you share the test results as you see them along with the versions of everything you're using?

**Comment by ikonst** [comment]
> You also have a defaultdict named call_seconds which you're trying to determine the length of.

`call_seconds` is a `Dict[datetime, int]`. Basically I'm using it to count how many requests I'm making in a given second (since I'm truncating the datetime to second granularity).

> You seem to be expecting there to be at least 2 entries there. So what I'm not sure is what you expect to see there or what you are seeing

If I set a rate limiter to 30 times a second at most, and I do something 35 times, and the dictionary ends up being just 1 item, it means that all 35 times were done in a single second.

> And I frankly don't have very much time to set up an environment in the next 5 minutes to re-run your test.

The environment is trivial to reproduce:
```console
mkdir rush
cd rush
virtualenv venv 
. venv/bin/activate
pip install rush gevent pytest
```
then:
```console
pytest test.py
```

> Could you share the test results as you see them along with the versions of everything you're using?

```
$ pip list
Package            Version
------------------ ---------
atomicwrites       1.3.0
attrs              19.1.0
gevent             1.4.0
greenlet           0.4.15
importlib-metadata 0.19
more-itertools     7.2.0
packaging          19.1
pip                19.2.2
pluggy             0.12.0
py                 1.8.0
pyparsing          2.4.2
pytest             5.1.1
rush               2018.12.1
setuptools         41.2.0
six                1.12.0
wcwidth            0.1.7
wheel              0.33.6
zipp               0.5.2
```
but, again, this is just the result of naively running `pip install rush gevent pytest` as of today.****

**Comment by sigmavirus24** [comment]
So I suspect this is an issue with the DictionaryStore and not with the library itself. As [documented](https://rush.readthedocs.io/en/latest/) the DictionaryStore is really there for basic testing but I highly doubt it will behave appropriately in this scenario.

I suspect if you tested with something like Redis you'd see the behaviour you're expecting.

**Comment by ikonst** [comment]
Thanks. I can try to have a look, although it's surprising that the `PeriodicLimiter` works just fine -- i.e. in my actual code, it helps me maintain a sustained RPS (also validated from the stats of the server that I'm calling).

I'm not using redis since I don't need a global rate limit. Coincidentally we have rate limiting "as a service" in my organization. My goal with using rush is to prevent unnecessary roundtrips to a server by throttling the requests locally first.

**Comment by sigmavirus24** [comment]
@ikonst also, I want to make sure that you fully understand how GCRA rate limiting is supposed to work. There's a [blog post](https://blog.ian.stapletoncordas.co/2018/12/understanding-generic-cell-rate-limiting.html) that explains it but the short answer is that the rate-limit regenerates. And as far as I'm concerned, it's working as expected. To verify this, (since it's the weekend and I finally have 5 minutes) I set up my environment like above and ran the test with some print debugging (because I'm super fancy like that :wink:). Here's the output I captured:

```
-------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------
RateLimitResult(limit=30, limited=False, remaining=29, reset_after=datetime.timedelta(days=-1, seconds=86399), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=28, reset_after=datetime.timedelta(microseconds=33073), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=27, reset_after=datetime.timedelta(microseconds=66260), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=26, reset_after=datetime.timedelta(microseconds=99475), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=25, reset_after=datetime.timedelta(microseconds=132697), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=24, reset_after=datetime.timedelta(microseconds=165925), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=23, reset_after=datetime.timedelta(microseconds=197919), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=22, reset_after=datetime.timedelta(microseconds=231020), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=21, reset_after=datetime.timedelta(microseconds=264215), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=20, reset_after=datetime.timedelta(microseconds=297430), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=19, reset_after=datetime.timedelta(microseconds=330654), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=18, reset_after=datetime.timedelta(microseconds=363880), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=17, reset_after=datetime.timedelta(microseconds=397107), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=16, reset_after=datetime.timedelta(microseconds=430335), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=15, reset_after=datetime.timedelta(microseconds=463562), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=14, reset_after=datetime.timedelta(microseconds=496781), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=13, reset_after=datetime.timedelta(microseconds=530005), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=12, reset_after=datetime.timedelta(microseconds=563235), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=11, reset_after=datetime.timedelta(microseconds=596464), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=10, reset_after=datetime.timedelta(microseconds=629694), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=9, reset_after=datetime.timedelta(microseconds=662926), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=8, reset_after=datetime.timedelta(microseconds=696157), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=7, reset_after=datetime.timedelta(microseconds=729389), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=6, reset_after=datetime.timedelta(microseconds=762622), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=5, reset_after=datetime.timedelta(microseconds=795854), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=4, reset_after=datetime.timedelta(microseconds=829072), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=3, reset_after=datetime.timedelta(microseconds=862285), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=2, reset_after=datetime.timedelta(microseconds=895514), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=928743), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=True, remaining=0, reset_after=datetime.timedelta(microseconds=961972), retry_after=datetime.timedelta(microseconds=28648))
sleeping
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=932595), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=True, remaining=0, reset_after=datetime.timedelta(microseconds=965443), retry_after=datetime.timedelta(microseconds=32119))
sleeping
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=932736), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=True, remaining=0, reset_after=datetime.timedelta(microseconds=965715), retry_after=datetime.timedelta(microseconds=32391))
sleeping
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=932463), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=True, remaining=0, reset_after=datetime.timedelta(microseconds=965413), retry_after=datetime.timedelta(microseconds=32089))
sleeping
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=932425), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=True, remaining=0, reset_after=datetime.timedelta(microseconds=965393), retry_after=datetime.timedelta(microseconds=32069))
sleeping
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=932644), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=True, remaining=0, reset_after=datetime.timedelta(microseconds=965529), retry_after=datetime.timedelta(microseconds=32205))
sleeping
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=932463), retry_after=datetime.timedelta(days=-1, seconds=86399))
defaultdict(<function test_rate_limit.<locals>.<lambda> at 0x7f8141808680>, {datetime.datetime(2019, 8, 24, 13, 13, 22, tzinfo=datetime.timezone.utc): 35})
```

Let me "zoom" in on the relevant bits to me:

```
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=928743), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=True, remaining=0, reset_after=datetime.timedelta(microseconds=961972), retry_after=datetime.timedelta(microseconds=28648))
sleeping
RateLimitResult(limit=30, limited=False, remaining=1, reset_after=datetime.timedelta(microseconds=932595), retry_after=datetime.timedelta(days=-1, seconds=86399))
RateLimitResult(limit=30, limited=True, remaining=0, reset_after=datetime.timedelta(microseconds=965443), retry_after=datetime.timedelta(microseconds=32119))
```

You can see that we bounce back and forth between being rate-limited and having a single request remaining. That's the bucket regenerating. Another way to think of this (as described in the blog post) is that we've filled the bucket but there's a steady leak in the bucket. So the time it takes us to leak enough to be able to get that 1 back is ~30000 microseconds. Because 30000 microseconds is (roughly) the time it takes for the bucket to leak, it makes sense to me that this would all happen within 1 second.

The `PeriodicLimiter` is (as documented) strict within a time period. The GCRA limiter acts exactly as it is supposed to. There are examples of its usage elsewhere in the world. The easiest (perhaps) to interact with would be the Heroku API.

**Comment by ikonst** [comment]
So I'd get the expected result if I'd first "empty the bucket"?
```py
for _ in range(rate_per_sec):
  throttle.check('my_request', 1)
```

(btw, this seems to be not the same as `throttle.check('my_request', rate_per_sec)`)

**Comment by sigmavirus24** [comment]
The behaviour you're seeing is what I expect from this. Your expectations are mismatched with what the GCRA implementation is _supposed_ to do.

It seems like you're expecting the behaviour of: I started making calls that count against a rate-limit at 9:30:30.000000 and I expect at 9:30:31.000000 that my ratelimit has reset regradless of what time I exhaust it at. That is emphatically not the design of GCRA.

Instead, GCRA looks at a sliding window (as that blog post explains). So the current time of the latest request is constantly catching up to the next window that will leak some of the used up limit. That point in the future will always be less than your period.

I'm not going to regurgitate that blog post, so I encourage you to read it and understand it.

**Comment by sigmavirus24** [comment]
So I think what you want is the Periodic Limiter then. GCRA is not designed to only allow N requests in a period of time. It's not strict because it wasn't designed to be a hard cut-off algorithm. It was designed to be a [Leaky Bucket](https://en.wikipedia.org/wiki/Leaky_bucket)

To be certain I'm understanding you, let me try to rephrase here.

You have a local client ("my client") that's talking to a server ("my server") that has the 30 requests/second rate-limit. You want the client to be able to "back-off" (or wait) to ensure that it doesn't exhaust the rate-limit and cause you to wait for the next second. Is this much right?

Because you don't want your client to be rate-limited by the server, you want your limiter to be slightly pessimistic (or to view the potential result of applying the limiter, e.g., with `Throttle.peek()`).
